# Project information
site_name: NextPilot
site_url: https://nextpilot.cn
site_author: LaterComer
site_description: NextPilot, a powerfull, scalable and advanced autopilot.

# Repository
repo_name: nextpilot.github.io
repo_url: https://github.com/nextpilot/nextpilot.github.io

use_directory_urls: false

# Copyright
copyright: Copyright &copy; 2015-2024 <a href="https://docs.nextpilot.cn">Nextpilot Develop Team</a>, Maintained by <a href="https://github.com/comerlater">LaterComer</a>.

# nav:
#   - HOME: index.md
#   - 关于我们: about/
#   - 解决方案: solution/
#   - 社区支持: community

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    # - navigation.footer
    # - navigation.sections
    - navigation.top
    - navigation.path
    - seach.highlight
    - search.suggest
    - search.share
    - toc.follow
  language: zh

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
      tab_length: 2

not_in_nav: |
  /**/SUMMARY.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nextpilot/nextpilot-flight-control/
      name: nextpilot/nextpilot-flight-control
    - icon: fontawesome/regular/file-lines
      link: https://docs.nextpilot.cn/develop
    - icon: fontawesome/regular/hand
      link: https://docs.nextpilot.cn/manual
